### PR TITLE
support save and initial data

### PR DESCRIPTION
**Pull request by gaboelnuevo**

### CODE REVIEW

**Comment by gaboelnuevo** [comment]
Congrats your project run very well with expo and very util for draw signatures.

I made some improvements such as allow export to SVG and rounded edges in the strokes and expect you like it.

Example:

```
import React from 'react';
import { StyleSheet, Text, View, Button, Dimensions } from 'react-native';
import RNDraw from 'rn-draw';

const {height, width} = Dimensions.get('window');

export default class App extends React.Component {
  state = {
    strokes: []
  }

  _renderToolBar(){
    return (
      <View style={{flexDirection: 'row', flexWrap: 'wrap', marginVertical: 5, justifyContent: 'space-between'}}>
        <Button title="Undo" onPress={() => this._undo && this._undo()}/>
        <Button title="Clear" onPress={() => this._clear && this._clear()}/>
        <Button title="Save" onPress={() => this._save() }/>
      </View>
    )
  }

  _save() {
    if(this.draw){
      console.log(this.draw.exportToSVG());
    }
  }

  onChangeStrokes(strokes) {
    this.setState({strokes});
  }

  render() {
    return (
      <View style={styles.container}>
        <View style={{flex: 1, width: width}}>
          <RNDraw
              ref={(draw) => { this.draw = draw; }}
              strokes={this.state.strokes}
              containerStyle={{backgroundColor: 'rgba(0,0,0,0.01)'}}
              rewind={(undo) => {this._undo = undo}}
              clear={(clear) => {this._clear = clear}}
              color={'#000000'}
              strokeWidth={4}
              onChangeStrokes={this.onChangeStrokes.bind(this)}
          />
        </View>
        { this._renderToolBar() }
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

An other thing that I found is a error in drawing points for example dots or the point above the letter "i". If you can see I fixed it. 

Att. Gabriel Sabillon

**Comment by julianbonomini** [comment]
Excelent, do you have this code upload in npm? Cause I need it really quick and I dont know if the ower will accept the PR soon.

**Comment by gaboelnuevo** [comment]
No. Look in this dependencies https://github.com/gaboelnuevo/expo-paint/blob/master/package.json how I installed this branch from github if you prefer fork from my repo and pull this branch.

**Comment by jayeszee** [comment]
Sorry for the delay guys! I've been quite busy lately myself. I'll take a look at it and test it this week . Thanks for contributing :]

**Review by jayeszee — APPROVED** [review]

**Pull request merged**
